// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.0
//
// <auto-generated>
//
// Generated from file `WMTS.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __G__MyProject_IceServer_WMTS_WMTS_src_generate_src_WMTS_h__
#define __G__MyProject_IceServer_WMTS_WMTS_src_generate_src_WMTS_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <OWS.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 0
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace WMTSMODULE
{

class WMTS;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::WMTSMODULE::WMTS>&);
::IceProxy::Ice::Object* upCast(::IceProxy::WMTSMODULE::WMTS*);

}

}

namespace WMTSMODULE
{

class WMTS;
bool operator==(const WMTS&, const WMTS&);
bool operator<(const WMTS&, const WMTS&);
::Ice::Object* upCast(::WMTSMODULE::WMTS*);
typedef ::IceInternal::Handle< ::WMTSMODULE::WMTS> WMTSPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::WMTSMODULE::WMTS> WMTSPrx;
void __patch(WMTSPtr&, const ::Ice::ObjectPtr&);

}

namespace WMTSMODULE
{

struct GetTileParameter
{
    ::std::string layer;
    ::std::string style;
    ::std::string format;
    ::Ice::Int level;
    ::Ice::Int row;
    ::Ice::Int col;

    bool operator==(const GetTileParameter& __rhs) const
    {
        if(this == &__rhs)
        {
            return true;
        }
        if(layer != __rhs.layer)
        {
            return false;
        }
        if(style != __rhs.style)
        {
            return false;
        }
        if(format != __rhs.format)
        {
            return false;
        }
        if(level != __rhs.level)
        {
            return false;
        }
        if(row != __rhs.row)
        {
            return false;
        }
        if(col != __rhs.col)
        {
            return false;
        }
        return true;
    }

    bool operator<(const GetTileParameter& __rhs) const
    {
        if(this == &__rhs)
        {
            return false;
        }
        if(layer < __rhs.layer)
        {
            return true;
        }
        else if(__rhs.layer < layer)
        {
            return false;
        }
        if(style < __rhs.style)
        {
            return true;
        }
        else if(__rhs.style < style)
        {
            return false;
        }
        if(format < __rhs.format)
        {
            return true;
        }
        else if(__rhs.format < format)
        {
            return false;
        }
        if(level < __rhs.level)
        {
            return true;
        }
        else if(__rhs.level < level)
        {
            return false;
        }
        if(row < __rhs.row)
        {
            return true;
        }
        else if(__rhs.row < row)
        {
            return false;
        }
        if(col < __rhs.col)
        {
            return true;
        }
        else if(__rhs.col < col)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const GetTileParameter& __rhs) const
    {
        return !operator==(__rhs);
    }
    bool operator<=(const GetTileParameter& __rhs) const
    {
        return operator<(__rhs) || operator==(__rhs);
    }
    bool operator>(const GetTileParameter& __rhs) const
    {
        return !operator<(__rhs) && !operator==(__rhs);
    }
    bool operator>=(const GetTileParameter& __rhs) const
    {
        return !operator<(__rhs);
    }
};

}

namespace Ice
{
template<>
struct StreamableTraits< ::WMTSMODULE::GetTileParameter>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 15;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::WMTSMODULE::GetTileParameter, S>
{
    static void write(S* __os, const ::WMTSMODULE::GetTileParameter& v)
    {
        __os->write(v.layer);
        __os->write(v.style);
        __os->write(v.format);
        __os->write(v.level);
        __os->write(v.row);
        __os->write(v.col);
    }
};

template<class S>
struct StreamReader< ::WMTSMODULE::GetTileParameter, S>
{
    static void read(S* __is, ::WMTSMODULE::GetTileParameter& v)
    {
        __is->read(v.layer);
        __is->read(v.style);
        __is->read(v.format);
        __is->read(v.level);
        __is->read(v.row);
        __is->read(v.col);
    }
};

}

namespace WMTSMODULE
{

class Callback_WMTS_GetCapabilities_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_WMTS_GetCapabilities_Base> Callback_WMTS_GetCapabilitiesPtr;

class Callback_WMTS_GetTile_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_WMTS_GetTile_Base> Callback_WMTS_GetTilePtr;

class Callback_WMTS_GetFeatureInfo_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_WMTS_GetFeatureInfo_Base> Callback_WMTS_GetFeatureInfoPtr;

}

namespace IceProxy
{

namespace WMTSMODULE
{

class WMTS : virtual public ::IceProxy::OWSMODULE::DataOperation
{
public:

    ::OWSMODULE::OWSTask GetCapabilities()
    {
        return GetCapabilities(0);
    }
    ::OWSMODULE::OWSTask GetCapabilities(const ::Ice::Context& __ctx)
    {
        return GetCapabilities(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_GetCapabilities(const ::IceInternal::Function<void (const ::OWSMODULE::OWSTask&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_GetCapabilities(0, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_GetCapabilities(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_GetCapabilities(0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_GetCapabilities(const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::OWSMODULE::OWSTask&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_GetCapabilities(&ctx, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_GetCapabilities(const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_GetCapabilities(&ctx, ::Ice::newCallback(completed, sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_GetCapabilities(const ::Ice::Context* ctx, const ::IceInternal::Function<void (const ::OWSMODULE::OWSTask&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception, const ::IceInternal::Function<void (bool)>& sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::OWSMODULE::OWSTask&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::WMTSMODULE::WMTSPrx __proxy = ::WMTSMODULE::WMTSPrx::uncheckedCast(__result->getProxy());
                ::OWSMODULE::OWSTask __ret;
                try
                {
                    __ret = __proxy->end_GetCapabilities(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::OWSMODULE::OWSTask&)> _response;
        };
        return begin_GetCapabilities(ctx, new Cpp11CB(response, exception, sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_GetCapabilities()
    {
        return begin_GetCapabilities(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_GetCapabilities(const ::Ice::Context& __ctx)
    {
        return begin_GetCapabilities(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_GetCapabilities(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_GetCapabilities(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_GetCapabilities(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_GetCapabilities(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_GetCapabilities(const ::WMTSMODULE::Callback_WMTS_GetCapabilitiesPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_GetCapabilities(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_GetCapabilities(const ::Ice::Context& __ctx, const ::WMTSMODULE::Callback_WMTS_GetCapabilitiesPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_GetCapabilities(&__ctx, __del, __cookie);
    }

    ::OWSMODULE::OWSTask end_GetCapabilities(const ::Ice::AsyncResultPtr&);
    
private:

    ::OWSMODULE::OWSTask GetCapabilities(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_GetCapabilities(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::OWSMODULE::OWSTask GetTile(const ::WMTSMODULE::GetTileParameter& parameter)
    {
        return GetTile(parameter, 0);
    }
    ::OWSMODULE::OWSTask GetTile(const ::WMTSMODULE::GetTileParameter& parameter, const ::Ice::Context& __ctx)
    {
        return GetTile(parameter, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_GetTile(const ::WMTSMODULE::GetTileParameter& parameter, const ::IceInternal::Function<void (const ::OWSMODULE::OWSTask&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_GetTile(parameter, 0, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_GetTile(const ::WMTSMODULE::GetTileParameter& parameter, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_GetTile(parameter, 0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_GetTile(const ::WMTSMODULE::GetTileParameter& parameter, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::OWSMODULE::OWSTask&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_GetTile(parameter, &ctx, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_GetTile(const ::WMTSMODULE::GetTileParameter& parameter, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_GetTile(parameter, &ctx, ::Ice::newCallback(completed, sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_GetTile(const ::WMTSMODULE::GetTileParameter& parameter, const ::Ice::Context* ctx, const ::IceInternal::Function<void (const ::OWSMODULE::OWSTask&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception, const ::IceInternal::Function<void (bool)>& sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::OWSMODULE::OWSTask&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::WMTSMODULE::WMTSPrx __proxy = ::WMTSMODULE::WMTSPrx::uncheckedCast(__result->getProxy());
                ::OWSMODULE::OWSTask __ret;
                try
                {
                    __ret = __proxy->end_GetTile(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::OWSMODULE::OWSTask&)> _response;
        };
        return begin_GetTile(parameter, ctx, new Cpp11CB(response, exception, sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_GetTile(const ::WMTSMODULE::GetTileParameter& parameter)
    {
        return begin_GetTile(parameter, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_GetTile(const ::WMTSMODULE::GetTileParameter& parameter, const ::Ice::Context& __ctx)
    {
        return begin_GetTile(parameter, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_GetTile(const ::WMTSMODULE::GetTileParameter& parameter, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_GetTile(parameter, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_GetTile(const ::WMTSMODULE::GetTileParameter& parameter, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_GetTile(parameter, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_GetTile(const ::WMTSMODULE::GetTileParameter& parameter, const ::WMTSMODULE::Callback_WMTS_GetTilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_GetTile(parameter, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_GetTile(const ::WMTSMODULE::GetTileParameter& parameter, const ::Ice::Context& __ctx, const ::WMTSMODULE::Callback_WMTS_GetTilePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_GetTile(parameter, &__ctx, __del, __cookie);
    }

    ::OWSMODULE::OWSTask end_GetTile(const ::Ice::AsyncResultPtr&);
    
private:

    ::OWSMODULE::OWSTask GetTile(const ::WMTSMODULE::GetTileParameter&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_GetTile(const ::WMTSMODULE::GetTileParameter&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::OWSMODULE::OWSTask GetFeatureInfo(const ::WMTSMODULE::GetTileParameter& parameter, ::Ice::Int I, ::Ice::Int J, const ::std::string& information)
    {
        return GetFeatureInfo(parameter, I, J, information, 0);
    }
    ::OWSMODULE::OWSTask GetFeatureInfo(const ::WMTSMODULE::GetTileParameter& parameter, ::Ice::Int I, ::Ice::Int J, const ::std::string& information, const ::Ice::Context& __ctx)
    {
        return GetFeatureInfo(parameter, I, J, information, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_GetFeatureInfo(const ::WMTSMODULE::GetTileParameter& parameter, ::Ice::Int I, ::Ice::Int J, const ::std::string& information, const ::IceInternal::Function<void (const ::OWSMODULE::OWSTask&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_GetFeatureInfo(parameter, I, J, information, 0, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_GetFeatureInfo(const ::WMTSMODULE::GetTileParameter& parameter, ::Ice::Int I, ::Ice::Int J, const ::std::string& information, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_GetFeatureInfo(parameter, I, J, information, 0, ::Ice::newCallback(completed, sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_GetFeatureInfo(const ::WMTSMODULE::GetTileParameter& parameter, ::Ice::Int I, ::Ice::Int J, const ::std::string& information, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::OWSMODULE::OWSTask&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_GetFeatureInfo(parameter, I, J, information, &ctx, response, exception, sent);
    }
    ::Ice::AsyncResultPtr
    begin_GetFeatureInfo(const ::WMTSMODULE::GetTileParameter& parameter, ::Ice::Int I, ::Ice::Int J, const ::std::string& information, const ::Ice::Context& ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_GetFeatureInfo(parameter, I, J, information, &ctx, ::Ice::newCallback(completed, sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_GetFeatureInfo(const ::WMTSMODULE::GetTileParameter& parameter, ::Ice::Int I, ::Ice::Int J, const ::std::string& information, const ::Ice::Context* ctx, const ::IceInternal::Function<void (const ::OWSMODULE::OWSTask&)>& response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& exception, const ::IceInternal::Function<void (bool)>& sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (const ::OWSMODULE::OWSTask&)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::WMTSMODULE::WMTSPrx __proxy = ::WMTSMODULE::WMTSPrx::uncheckedCast(__result->getProxy());
                ::OWSMODULE::OWSTask __ret;
                try
                {
                    __ret = __proxy->end_GetFeatureInfo(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (const ::OWSMODULE::OWSTask&)> _response;
        };
        return begin_GetFeatureInfo(parameter, I, J, information, ctx, new Cpp11CB(response, exception, sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_GetFeatureInfo(const ::WMTSMODULE::GetTileParameter& parameter, ::Ice::Int I, ::Ice::Int J, const ::std::string& information)
    {
        return begin_GetFeatureInfo(parameter, I, J, information, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_GetFeatureInfo(const ::WMTSMODULE::GetTileParameter& parameter, ::Ice::Int I, ::Ice::Int J, const ::std::string& information, const ::Ice::Context& __ctx)
    {
        return begin_GetFeatureInfo(parameter, I, J, information, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_GetFeatureInfo(const ::WMTSMODULE::GetTileParameter& parameter, ::Ice::Int I, ::Ice::Int J, const ::std::string& information, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_GetFeatureInfo(parameter, I, J, information, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_GetFeatureInfo(const ::WMTSMODULE::GetTileParameter& parameter, ::Ice::Int I, ::Ice::Int J, const ::std::string& information, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_GetFeatureInfo(parameter, I, J, information, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_GetFeatureInfo(const ::WMTSMODULE::GetTileParameter& parameter, ::Ice::Int I, ::Ice::Int J, const ::std::string& information, const ::WMTSMODULE::Callback_WMTS_GetFeatureInfoPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_GetFeatureInfo(parameter, I, J, information, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_GetFeatureInfo(const ::WMTSMODULE::GetTileParameter& parameter, ::Ice::Int I, ::Ice::Int J, const ::std::string& information, const ::Ice::Context& __ctx, const ::WMTSMODULE::Callback_WMTS_GetFeatureInfoPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_GetFeatureInfo(parameter, I, J, information, &__ctx, __del, __cookie);
    }

    ::OWSMODULE::OWSTask end_GetFeatureInfo(const ::Ice::AsyncResultPtr&);
    
private:

    ::OWSMODULE::OWSTask GetFeatureInfo(const ::WMTSMODULE::GetTileParameter&, ::Ice::Int, ::Ice::Int, const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_GetFeatureInfo(const ::WMTSMODULE::GetTileParameter&, ::Ice::Int, ::Ice::Int, const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<WMTS> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_secure(bool __secure) const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_twoway() const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_oneway() const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_batchOneway() const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_datagram() const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_batchDatagram() const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_compress(bool __compress) const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_timeout(int __timeout) const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<WMTS> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<WMTS*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace WMTSMODULE
{

class WMTS : virtual public ::IceDelegate::OWSMODULE::DataOperation
{
public:

    virtual ::OWSMODULE::OWSTask GetCapabilities(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::OWSMODULE::OWSTask GetTile(const ::WMTSMODULE::GetTileParameter&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual ::OWSMODULE::OWSTask GetFeatureInfo(const ::WMTSMODULE::GetTileParameter&, ::Ice::Int, ::Ice::Int, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace WMTSMODULE
{

class WMTS : virtual public ::IceDelegate::WMTSMODULE::WMTS,
             virtual public ::IceDelegateM::OWSMODULE::DataOperation
{
public:

    virtual ::OWSMODULE::OWSTask GetCapabilities(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::OWSMODULE::OWSTask GetTile(const ::WMTSMODULE::GetTileParameter&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::OWSMODULE::OWSTask GetFeatureInfo(const ::WMTSMODULE::GetTileParameter&, ::Ice::Int, ::Ice::Int, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace WMTSMODULE
{

class WMTS : virtual public ::IceDelegate::WMTSMODULE::WMTS,
             virtual public ::IceDelegateD::OWSMODULE::DataOperation
{
public:

    virtual ::OWSMODULE::OWSTask GetCapabilities(const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::OWSMODULE::OWSTask GetTile(const ::WMTSMODULE::GetTileParameter&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual ::OWSMODULE::OWSTask GetFeatureInfo(const ::WMTSMODULE::GetTileParameter&, ::Ice::Int, ::Ice::Int, const ::std::string&, const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace WMTSMODULE
{

class WMTS : virtual public ::OWSMODULE::DataOperation
{
public:

    typedef WMTSPrx ProxyType;
    typedef WMTSPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual ::OWSMODULE::OWSTask GetCapabilities(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___GetCapabilities(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::OWSMODULE::OWSTask GetTile(const ::WMTSMODULE::GetTileParameter&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___GetTile(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::OWSMODULE::OWSTask GetFeatureInfo(const ::WMTSMODULE::GetTileParameter&, ::Ice::Int, ::Ice::Int, const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___GetFeatureInfo(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const WMTS& l, const WMTS& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const WMTS& l, const WMTS& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace WMTSMODULE
{

template<class T>
class CallbackNC_WMTS_GetCapabilities : public Callback_WMTS_GetCapabilities_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::OWSMODULE::OWSTask&);

    CallbackNC_WMTS_GetCapabilities(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::WMTSMODULE::WMTSPrx __proxy = ::WMTSMODULE::WMTSPrx::uncheckedCast(__result->getProxy());
        ::OWSMODULE::OWSTask __ret;
        try
        {
            __ret = __proxy->end_GetCapabilities(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_WMTS_GetCapabilitiesPtr
newCallback_WMTS_GetCapabilities(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::OWSMODULE::OWSTask&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_WMTS_GetCapabilities<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_WMTS_GetCapabilitiesPtr
newCallback_WMTS_GetCapabilities(T* instance, void (T::*cb)(const ::OWSMODULE::OWSTask&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_WMTS_GetCapabilities<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_WMTS_GetCapabilities : public Callback_WMTS_GetCapabilities_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::OWSMODULE::OWSTask&, const CT&);

    Callback_WMTS_GetCapabilities(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::WMTSMODULE::WMTSPrx __proxy = ::WMTSMODULE::WMTSPrx::uncheckedCast(__result->getProxy());
        ::OWSMODULE::OWSTask __ret;
        try
        {
            __ret = __proxy->end_GetCapabilities(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_WMTS_GetCapabilitiesPtr
newCallback_WMTS_GetCapabilities(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::OWSMODULE::OWSTask&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_WMTS_GetCapabilities<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_WMTS_GetCapabilitiesPtr
newCallback_WMTS_GetCapabilities(T* instance, void (T::*cb)(const ::OWSMODULE::OWSTask&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_WMTS_GetCapabilities<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_WMTS_GetTile : public Callback_WMTS_GetTile_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::OWSMODULE::OWSTask&);

    CallbackNC_WMTS_GetTile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::WMTSMODULE::WMTSPrx __proxy = ::WMTSMODULE::WMTSPrx::uncheckedCast(__result->getProxy());
        ::OWSMODULE::OWSTask __ret;
        try
        {
            __ret = __proxy->end_GetTile(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_WMTS_GetTilePtr
newCallback_WMTS_GetTile(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::OWSMODULE::OWSTask&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_WMTS_GetTile<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_WMTS_GetTilePtr
newCallback_WMTS_GetTile(T* instance, void (T::*cb)(const ::OWSMODULE::OWSTask&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_WMTS_GetTile<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_WMTS_GetTile : public Callback_WMTS_GetTile_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::OWSMODULE::OWSTask&, const CT&);

    Callback_WMTS_GetTile(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::WMTSMODULE::WMTSPrx __proxy = ::WMTSMODULE::WMTSPrx::uncheckedCast(__result->getProxy());
        ::OWSMODULE::OWSTask __ret;
        try
        {
            __ret = __proxy->end_GetTile(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_WMTS_GetTilePtr
newCallback_WMTS_GetTile(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::OWSMODULE::OWSTask&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_WMTS_GetTile<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_WMTS_GetTilePtr
newCallback_WMTS_GetTile(T* instance, void (T::*cb)(const ::OWSMODULE::OWSTask&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_WMTS_GetTile<T, CT>(instance, cb, excb, sentcb);
}

template<class T>
class CallbackNC_WMTS_GetFeatureInfo : public Callback_WMTS_GetFeatureInfo_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(const ::OWSMODULE::OWSTask&);

    CallbackNC_WMTS_GetFeatureInfo(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::WMTSMODULE::WMTSPrx __proxy = ::WMTSMODULE::WMTSPrx::uncheckedCast(__result->getProxy());
        ::OWSMODULE::OWSTask __ret;
        try
        {
            __ret = __proxy->end_GetFeatureInfo(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_WMTS_GetFeatureInfoPtr
newCallback_WMTS_GetFeatureInfo(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::OWSMODULE::OWSTask&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_WMTS_GetFeatureInfo<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_WMTS_GetFeatureInfoPtr
newCallback_WMTS_GetFeatureInfo(T* instance, void (T::*cb)(const ::OWSMODULE::OWSTask&), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_WMTS_GetFeatureInfo<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_WMTS_GetFeatureInfo : public Callback_WMTS_GetFeatureInfo_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const ::OWSMODULE::OWSTask&, const CT&);

    Callback_WMTS_GetFeatureInfo(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::WMTSMODULE::WMTSPrx __proxy = ::WMTSMODULE::WMTSPrx::uncheckedCast(__result->getProxy());
        ::OWSMODULE::OWSTask __ret;
        try
        {
            __ret = __proxy->end_GetFeatureInfo(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_WMTS_GetFeatureInfoPtr
newCallback_WMTS_GetFeatureInfo(const IceUtil::Handle<T>& instance, void (T::*cb)(const ::OWSMODULE::OWSTask&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_WMTS_GetFeatureInfo<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_WMTS_GetFeatureInfoPtr
newCallback_WMTS_GetFeatureInfo(T* instance, void (T::*cb)(const ::OWSMODULE::OWSTask&, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_WMTS_GetFeatureInfo<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
